.github/workflows/nodejs.yml

Changed webpack versions
No
No

ci: updated

---

package-lock.json
package.json
src/options.js

chore: bump to schema-utils 3.x

---

README.md
declarations/getESLint.d.ts
declarations/index.d.ts
declarations/linter.d.ts
declarations/options.d.ts
package-lock.json
package.json
src/index.js
src/options.js
src/options.json
src/utils.js
test/exclude.test.js
test/fixtures/exclude-entry.js
test/fixtures/exclude-folder-entry.js
test/fixtures/folder/error.js
test/utils.test.js

feat: exclude option

---

package-lock.json
package.json
tsconfig.json

chore: updates

---

src/linter.js
test/watch.test.js

My last PR fix missed one edge case. If you fix all the errors in a file, we still want to keep reporting the other messages.

Fix 44 again

---

src/index.js
test/lint-dirty-modules-only.test.js

fix: lint dirty modules only

---

README.md

docs: formatting

---

declarations/ESLintError.d.ts

fix: types

---

README.md
src/index.js

Exclude `node_modules` folder from root.

fix: exclude node_modules root

---

src/utils.js
test/fixtures/[symbols]/error.js
test/fixtures/[symbols]/symbols-entry.js
test/symbols.test.js

fix: context with symbols

---

declarations/linter.d.ts
declarations/utils.d.ts
package-lock.json
package.json
src/utils.js
test/utils.test.js

fix: resolve paths and normalize

---

.github/workflows/nodejs.yml

Use `matrix.node-version`
None
No

ci: nodejs.yml

---

package-lock.json
package.json

forgot to remove arrify https://github.com/webpack-contrib/eslint-webpack-plugin/pull/109
No
We really should avoid using simple package for simple actions, it is increase `node_modules` size and create transitive problems

chore(remove): arrify from deps

---

.github/workflows/nodejs.yml

use npm cache across test jobs
no

chore: use npm cache

---

.github/workflows/nodejs.yml

update `codecov-action` to v2 in workflow
None
No

ci: update `codecov-action` to v2

---

src/index.js
test/child-compiler.test.js
test/fixtures/child-entry.js

fix: child compiler lint

---

README.md

Some of the links weren't working properly and fixed smaller typos

chore: fix typo and fixed broken links

---

declarations/getESLint.d.ts
package-lock.json
package.json
src/getESLint.js

Update [`schema-utils`](https://github.com/webpack/schema-utils) to `v4.0.0`
No
No

chore: update deps

---

README.md

You don't need to “install” when using yarn add

docs(readme): remove install when using yarn add

---

README.md

Update note and warning in readme.md file

chore: enhance readme.md

---

README.md
commitlint.config.js

style: formatting

---

package-lock.json
package.json
test/utils.test.js

update jest to the latest version
No
No

chore: update jest to the latest version

---

package-lock.json
package.json
src/index.js

update dependencies to the latest version
No
No

chore: update dependencies to the latest version

---

.eslintrc.js
.github/workflows/nodejs.yml
README.md
package-lock.json
package.json
src/getESLint.js
src/index.js
src/linter.js
src/worker.js
test/fixtures/query-entry.js
test/fixtures/resource-query-entry.js
test/flat-config.test.js
test/threads.test.js
test/watch.test.js
tsconfig.json
types/getESLint.d.ts
types/linter.d.ts
types/worker.d.ts

feat: support eslint 9

---

.github/workflows/nodejs.yml

ci: fix name
